// frontEndVue/src/components/Peliculas.vue
<template>
    <section id="content">
        <h2 class="subheader">Películas</h2>
        <!--Listado de articulos-->                
        <div id="articles">
            <article class="article-item" v-for="pelicula in peliculas" v-bind:key="pelicula.title">
                <div class="image-wrap">
                    <img :src="pelicula.image" :alt="pelicula.title" :title="pelicula.title" />
                </div>
                <h2>{{pelicula.title}}</h2>
                <span class="date">
                    {{pelicula.year}}
                </span>
                <a href="#">Leer más</a>
                
                <div class="clearfix"></div>
            </article>
            {{peliculas[0].title}}
        </div>
    </section>
</template>

<script>
export default {
    name: 'Peliculas',
    data(){
        return{
            peliculas: [
                {title: 'Batman vs Superman', year: 2017, image: ""},
                {title: 'Gran Torino', year: 2015, image: ""},
                {title: 'El Señor de los Anillos', year: 2003, image: ""},
                {title: 'Spiderman', year: 2002, image: ""}
            ]
        }
    }
}
</script>

// frontEndAngular/src/app/components/peliculas/peliculas.component.ts
import { Component, OnInit, DoCheck, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-peliculas',
  templateUrl: './peliculas.component.html',
  styleUrls: ['./peliculas.component.css']
})
export class PeliculasComponent implements OnInit, DoCheck, OnDestroy {

  public titulo: string;

  constructor() {
    this.titulo = "Componente Peliculas";
    console.log("Constructor lanzado");
  }

  cambiarTitulo(){
    this.titulo = "El titulo ha sido cambiado";
  }

  ngOnInit(): void {
    console.log("Evento OnInit lanzado / Componente iniciado");
  }

  ngDoCheck(): void {
    console.log("DoCheck lanzado");
  }

  ngOnDestroy(): void {
    console.log("OnDestroy lanzado: Se va a eliminar este componente");
  }

}

<app-slider
  [nombre]="'Películas'"
  [size]="'small'"
></app-slider>
<div class="center">
  <section id="content">
    <h1 class="subheader">{{titulo}}</h1>
    <button (click)="cambiarTitulo()">Pulsame</button>
    <hr/>
    <h2>Mostrar primera película</h2>
    {{peliculas[0].title}}
    <hr/>
    <h2>Número de películas</h2>

    <div *ngIf="peliculas.length <= 3">
      Hay pocas películas
    </div>
    <div *ngIf="peliculas.length > 3">
      Hay muchas películas
    </div>
    {{peliculas.length}}
    <hr/>
    <h2 class="subheader">Listado de películas</h2>

    <div id="articles" *ngIf="peliculas">
      <article class="article-item" id="article-template" *ngFor="let pelicula of peliculas">
          <div class="image-wrap">
              <img src={{pelicula.image}} alt={{pelicula.title}}/>
          </div>
          <h2>{{pelicula.title}}</h2>
          <span class="year" [ngClass]="{
                              'year-green': pelicula.year > 2016,
                              'year-red': pelicula.year <= 2018
                            }">
              {{pelicula.year}}
          </span>
          <a href="#">Leer más</a>

          <div class="clearfix"></div>
      </article>
    </div>
  </section>
  <app-sidebar></app-sidebar>
  <div class="clearfix"></div>
</div>
