// frontEndVue/src/components/Article.vue
<template>
    <div class="general">
        <div class="center">
            <section id="content">
                <article class="article-item article-detail" v-if="article">
                        <div class="image-wrap">
                            <img :src="url + 'get-image/' + article.image" :alt="article.title" v-if="article.image"/>
                            <img src="../assets/images/default-image.png" :alt="article.title" v-if="!article.image"/>
                        </div>
                        <h1 class="subheader">{{article.title}}</h1>
                        <span class="date">
                            {{article.date | moment("from", "now")}}
                        </span>
                        <p>{{article.content}}</p>
                        <div class="clearfix"></div>
                        <router-link to="/editar" class="btn btn-warning">Editar</router-link>
                        <router-link to="/eliminar" class="btn btn-danger">Eliminar</router-link>
                    </article>

            </section>
            <Sidebar></Sidebar>
            <div class="clearfix"></div>
        </div>
    </div>
</template>

<script>
import Sidebar from './Siderbar.vue';
import Global from '../Global';
import axios from 'axios';

export default {
    name: 'Article',
    components: {
        Sidebar
    },
    data(){
        return {
            url: Global.url,
            article: null
        }
    },
    mounted(){
        var articleId = this.$route.params.id;
        this.getArticle(articleId);
    },
    methods:{
        getArticle(articleId){
            axios.get(this.url + 'article/' + articleId).then(res => {
                console.log(res);
                if(res.data.status == 'success'){
                    this.article = res.data.article;
                }
            });
        }
    }
}
</script>

// frontEndAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { Global } from '../../services/global';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {

  public article: Article;
  public url: string = Global.url;
  constructor(
    public _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ) { }

  ngOnInit(): void {
    this._route.params.subscribe(params => {
      let id = params['id'];
      this._articleService.getArticle(id).subscribe(
        response => {
          //console.log(response);
          if(response.article){
            this.article = response.article;
          }else{
            this._router.navigate(['/home']);
          }
        }, error => {
          //console.log(error);
          this._router.navigate(['/home']);
        }
      );
    })

  }

}

<div class="center">
  <section id="content">
    <article class="article-item article-detail">
      <div class="image-wrap">
        <img src="{{url + 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image"/>
        <img src="assets/images/default.jpg" alt="{{article.title}}" *ngIf="!article.image"/>
      </div>
      <h1 class="subheader">{{article.title}}</h1>
      <span class="date">
        {{article.date | amLocale: 'es' | amTimeAgo}}
      </span>
      <p>{{article.content}}</p>

      <div class="buttons">
        <a href="#" class="btn btn-warning">Editar</a>
        <a href="#" class="btn btn-danger">Borrar</a>
      </div>
      <div class="clearfix"></div>
  </article>

  </section>
  <app-sidebar></app-sidebar>
  <div class="clearfix"></div>
</div>
