// frontEndVue/src/components/Articles.vue
<template>
    <div>
        <article class="article-item" v-for="article in articles" :key="article._id">
            <div class="image-wrap">
                <img :src="url + 'get-image/'+article.image" :alt="article.title" v-if="article.image"/>
                <img src="../assets/images/default-image.png" :alt="article.title" v-if="!article.image"/>
            </div>
            <h2>{{article.title}}</h2>
            <span class="date">
                {{article.date}}
            </span>
            <a href="#">Leer más</a>
            
            <div class="clearfix"></div>
        </article>
    </div>
</template>


<script>
export default {
    name: 'Articles',
    props: ['articles']
}
</script>

// frontEndAngular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Article } from 'src/app/models/article';
import { Global } from '../../services/global';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {

  public url: string;
  @Input() articles: Article[];

  constructor() {
    this.url = Global.url;
  }

  ngOnInit(): void {
  }

}

<div id="articles">
  <article class="article-item" *ngFor="let article of articles">
      <div class="image-wrap">
          <img src="{{url + 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image"/>
          <img src="assets/images/default.jpg" alt="{{article.title}}" *ngIf="!article.image"/>
      </div>
      <h2>{{article.title}}</h2>
      <span class="date">
          {{article.date}}
      </span>
      <a href="#">Leer más</a>
      <div class="clearfix"></div>
  </article>
</div>
