// frontEndVue/src/components/Blog.vue
<template>
    <div class="general">
        <Slider texto="Blog"></Slider>
        <div class="center">
            <section id="content">
                <h2 class="subheader">Blog</h2>

                <div id="articles" v-if="articles">
                    <article class="article-item" v-for="article in articles" :key="article._id">
                        <div class="image-wrap">
                            <img :src="url + 'get-image/'+article.image" :alt="article.title" v-if="article.image"/>
                            <img src="../assets/images/default-image.png" :alt="article.title" v-if="!article.image"/>
                        </div>
                        <h2>{{article.title}}</h2>
                        <span class="date">
                            {{article.date}}
                        </span>
                        <a href="#">Leer más</a>
                        
                        <div class="clearfix"></div>
                    </article>
                </div>

            </section>
            <Sidebar></Sidebar>
            <div class="clearfix"></div>
        </div>
    </div>
</template>

<script>
import Slider from './Slider.vue';
import Sidebar from './Siderbar.vue';
import axios from 'axios';
import Global from '../Global';

export default {
    name: 'Blog',
    components: {
        Slider,
        Sidebar
    },
    mounted(){
        this.getArticles();
    },
    data(){
        return {
            url: Global.url,
            articles: []
        }
    },
    methods: {
        getArticles(){
            axios.get(this.url + 'articles')
                .then(res => {
                    if(res.data.status == 'success'){
                        this.articles = res.data.articles;
                    }
                    console.log(this.articles);
                });
        }
    }
}
</script>

// frontEndAngular/src/app/components/blog/blog.component.ts
import { Component, OnInit } from '@angular/core';
import { Article } from 'src/app/models/article';
import { ArticleService } from '../../services/article.service';
import { Global } from '../../services/global';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.css'],
  providers: [ArticleService]
})
export class BlogComponent implements OnInit {
  public title: string;
  public articles: Article[];
  public url: string;

  constructor(
    private _articleService: ArticleService
  ) {
    this.title = "Blog";
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._articleService.getArticles().subscribe(
      response => {
        if(response.articles){
          this.articles = response.articles;
        }
        else{}
      },
      error => {
        console.log(error);
      }
    );
  }

}

<app-slider
  [nombre]="'Blog'"
  [size]="'small'"
></app-slider>
<div class="center">
  <section id="content">
    <h1 class="subheader">Blog</h1>
    <div id="articles">
      <article class="article-item" *ngFor="let article of articles">
          <div class="image-wrap">
              <img src="{{url + 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image"/>
              <img src="assets/images/default.jpg" alt="{{article.title}}" *ngIf="!article.image"/>
          </div>
          <h2>{{article.title}}</h2>
          <span class="date">
              {{article.date}}
          </span>
          <a href="#">Leer más</a>

          <div class="clearfix"></div>
      </article>
    </div>
  </section>
  <app-sidebar></app-sidebar>
  <div class="clearfix"></div>
</div>
