// frontEndVue/src/components/Formulario.vue
<template>
    <div class="general">
        <div class="center">
            <section id="content">
                <h2 class="subheader">Formulario</h2>
                <form class="mid-form" @submit.prevent="mostrarUsuario()">
                        <div class="form-group">
                            <label for="nombre">Nombre</label>
                            <input type="text" name="nombre" v-model="user.nombre"/>
                        </div>
                        <div class="form-group">
                            <label for="apellidos">Apellidos</label>
                            <input type="text" name="apellidos" v-model="user.apellidos"/>
                        </div>
                        <div class="form-group">
                            <label for="bio">Biografía</label>
                            <textarea name="bio" v-model="user.biografia"></textarea>
                        </div>
                        <div class="form-group radio-buttons">
                            <input type="radio" name="genero" value="hombre" checked v-model="user.genero"/>Hombre
                            <input type="radio" name="genero" value="mujer" v-model="user.genero"/>Mujer
                            <input type="radio" name="genero" value="otro" v-model="user.genero"/>Otro
                        </div>
                        <div class="clearfix"></div>
                        <input type="submit" value="Enviar" class="btn btn-success"/>

                    </form>
                    <div class="datos" v-if="user">
                        <h3>{{user.nombre + ' ' + user.apellidos}}</h3>
                    </div>
            </section>
            <Sidebar></Sidebar>
            <div class="clearfix"></div>
        </div>
    </div>
</template>

<script>
import Sidebar from './Siderbar.vue';
export default {
    name: 'Formulario',
    components: {
        Sidebar
    },
    data(){
        return {
            user: {
                nombre:'',
                apellidos: '',
                biografia: '',
                genero: ''
            }
        }
    },
    methods: {
        mostrarUsuario(){
            console.log(this.user);
        }
    }
}
</script>

// frontEndAngular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {
  public title: string;

  public user: any;

  constructor() {
    this.title = "Formulario";
    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    };
  }

  ngOnInit(): void {
  }

  onSubmit(){
    alert("Formulario Enviado");
    console.log(this.user);
  }

}

<app-slider
  [nombre]="'Formulario'"
  [size]="'small'"
></app-slider>
<div class="center">
  <section id="content">
    <h1 class="subheader">{{title}}</h1>

    <div id="datos-al-vuelo" *ngIf="user.nombre">
      <h1 class="subheader">Datos al Vuelo</h1>
      <ul>
        <li>{{user.nombre}}</li>
        <li>{{user.apellidos}}</li>
        <li>{{user.bio}}</li>
        <li>{{user.genero}}</li>
      </ul>
    </div>
    <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
          <label for="nombre">Nombre</label>
          <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre"/>
      </div>
      <div class="form-group">
          <label for="apellidos">Apellidos</label>
          <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos"/>
      </div>
      <div class="form-group">
          <label for="bio">Biografía</label>
          <textarea name="bio" #bio="ngModel" [(ngModel)]="user.bio"></textarea>
      </div>
      <div class="form-group radio-buttons">
          <input type="radio" name="genero" value="hombre" [(ngModel)]="user.genero"/>Hombre
          <input type="radio" name="genero" value="mujer" [(ngModel)]="user.genero"/>Mujer
          <input type="radio" name="genero" value="otro" [(ngModel)]="user.genero"/>Otro
      </div>
      <div class="clearfix"></div>
      <input type="submit" value="Enviar" class="btn btn-success"/>
    </form>
  </section>
  <app-sidebar></app-sidebar>
  <div class="clearfix"></div>
</div>
